### load your libraries

In [5]:
import pandas as pd #ingesting and transforming raw data
import ast #abstract syntax tree: converts string to python object

### load the dataset

In [21]:
customers = pd.read_csv("./data/customers.csv")
offers = pd.read_csv("./data/offers.csv")
events = pd.read_csv("./data/events.csv")

### Data exploration
* size of data
* data types
* observe inconsistencies in the dataset

In [23]:
# Size of the dataframe
tables = [customers, offers, events]
for i in tables:
    size = i.shape
    print(size)

(17000, 5)
(10, 6)
(306534, 4)

In [24]:
# Data types
# For customers
customers.dtypes

customer_id             str
became_member_on      int64
gender                  str
age                   int64
income              float64
dtype: object

In [25]:
# Data types
# For events
events.dtypes

customer_id      str
event            str
value            str
time           int64
dtype: object

In [26]:
# Data types
# For offers
offers.dtypes

offer_id        str
offer_type      str
difficulty    int64
reward        int64
duration      int64
channels        str
dtype: object

In [27]:
# Observe inconsistencies'
# for customers
customers.head()

                        customer_id  became_member_on gender  age    income
0  68be06ca386d4c31939f3a4f0e3dd783          20170212    NaN  118       NaN
1  0610b486422d4921ae7d2bf64640c50b          20170715      F   55  112000.0
2  38fe809add3b4fcf9315a9694bb96ff5          20180712    NaN  118       NaN
3  78afa995795e4d85b5d9ceeca43f5fef          20170509      F   75  100000.0
4  a03223e636434f42ac4c3df47e8bac43          20170804    NaN  118       NaN

In [28]:
# Observe inconsistencies'
# for offers
events.head()

,customer_id,event,value,time
0,78afa995795e4d85b5d9ceeca43f5fef,offer received,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0
1,a03223e636434f42ac4c3df47e8bac43,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0
2,e2127556f4f64592b11af22de27a7932,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0
3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0
4,68617ca6246f4fbc85e91a2a49552598,offer received,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0

In [29]:
# Observe inconsistencies'
# for offers
offers.head()

,offer_id,offer_type,difficulty,reward,duration,channels
0,ae264e3637204a6fb9bb56bc8210ddfd,bogo,10,10,7,"['email', 'mobile', 'social']"
1,4d5c57ea9a6940dd891ad53e9dbe8da0,bogo,10,10,5,"['web', 'email', 'mobile', 'social']"
2,3f207df678b143eea3cee63160fa8bed,informational,0,0,4,"['web', 'email', 'mobile']"
3,9b98b8c7a33c4b65b9aebfe6a799e6d9,bogo,5,5,7,"['web', 'email', 'mobile']"
4,0b1e1539f2cc45b7b9fa7c272da2e1d7,discount,20,5,10,"['web', 'email']"

## Customer Table Transformation

In [30]:
# Convert the became_member_on column to datetime format
customers['became_member_on'] = pd.to_datetime(customers['became_member_on'], format="%Y%m%d")

In [31]:
# Fill the null value in the income column with the average income
avg_income = float(customers['income'].mean())
avg_income = round(avg_income, 1)

# customers['income'].fillna(avg_income, inplace=True)
customers['income'] = customers['income'].fillna(avg_income)

## Offers Table Transformation

### We want to create a bridge table that satisfies 2NF

In [32]:
# Converting the strings to an original list

offers['channels'] = offers['channels'].apply(ast.literal_eval)

In [33]:
# explode the dataframe to meet the 1NF requirement
# create a junction table
offers_channels = offers[['offer_id', 'channels']]
offers_channels = offers_channels.explode('channels')

In [34]:
offers_transformed = offers.drop(columns=['channels'])
offers_transformed

,offer_id,offer_type,difficulty,reward,duration
0,ae264e3637204a6fb9bb56bc8210ddfd,bogo,10,10,7
1,4d5c57ea9a6940dd891ad53e9dbe8da0,bogo,10,10,5
2,3f207df678b143eea3cee63160fa8bed,informational,0,0,4
3,9b98b8c7a33c4b65b9aebfe6a799e6d9,bogo,5,5,7
4,0b1e1539f2cc45b7b9fa7c272da2e1d7,discount,20,5,10
5,2298d6c36e964ae4a3e7e9706d1fb8c2,discount,7,3,7
6,fafdcd668e3743c1bb461111dcafc2a4,discount,10,2,10
7,5a8bc65990b245e5a138643cd4eb9837,informational,0,0,3
8,f19421c1d4aa40978ebb69ca19b0e20d,bogo,5,5,5
9,2906b810c7d4411798c6938adc9daaa5,discount,10,2,7

## Event table Transformation

In [37]:
# convert the values from a string to dictionary
events['value'] = events['value'].apply(ast.literal_eval)

values_info = pd.json_normalize(events['value'])

# Clean up the value_info
if 'offer id' in values_info.columns:
    values_info['offer_id'] = values_info['offer_id'].fillna(values_info['offer id'])
    values_info = values_info.drop(columns=['offer id'])
else:
    print('no such columns')

events_transformed = events.drop(columns=['value'])
events_transformed = pd.concat([events_transformed, values_info], axis=1)  # merged two tables together

In [38]:
events_transformed

,customer_id,event,time,amount,offer_id,reward
0,78afa995795e4d85b5d9ceeca43f5fef,offer received,0,NaN,9b98b8c7a33c4b65b9aebfe6a799e6d9,NaN
1,a03223e636434f42ac4c3df47e8bac43,offer received,0,NaN,0b1e1539f2cc45b7b9fa7c272da2e1d7,NaN
2,e2127556f4f64592b11af22de27a7932,offer received,0,NaN,2906b810c7d4411798c6938adc9daaa5,NaN
3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,0,NaN,fafdcd668e3743c1bb461111dcafc2a4,NaN
4,68617ca6246f4fbc85e91a2a49552598,offer received,0,NaN,4d5c57ea9a6940dd891ad53e9dbe8da0,NaN
...,...,...,...,...,...,...
306529,b3a1272bc9904337b331bf348c3e8c17,transaction,714,1.59,NaN,NaN
306530,68213b08d99a4ae1b0dcb72aebd9aa35,transaction,714,9.53,NaN,NaN
306531,a00058cf10334a308c68e7631c529907,transaction,714,3.61,NaN,NaN
306532,76ddbd6576844afe811f1a3c0fbb5bec,transaction,714,3.53,NaN,NaN
306533,c02b10e8752c4d8e9b73f918558531f7,transaction,714,4.05,NaN,NaN

In [ ]:
# fill the null values in the amount column with 0.0
events_transformed['amount'] = events_transformed['amount'].fillna(0.0)

In [40]:
# fill the null values in the reward column with 0.0
events_transformed['reward'] = events_transformed['reward'].fillna(0.0)

In [ ]:
# change the time column to date time/ timedelta
# events_transformed['time'] = pd.to_timedelta(events_transformed['time'], unit="h")

In [41]:
events_transformed

,customer_id,event,time,amount,offer_id,reward
0,78afa995795e4d85b5d9ceeca43f5fef,offer received,0,0.00,9b98b8c7a33c4b65b9aebfe6a799e6d9,0.0
1,a03223e636434f42ac4c3df47e8bac43,offer received,0,0.00,0b1e1539f2cc45b7b9fa7c272da2e1d7,0.0
2,e2127556f4f64592b11af22de27a7932,offer received,0,0.00,2906b810c7d4411798c6938adc9daaa5,0.0
3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,0,0.00,fafdcd668e3743c1bb461111dcafc2a4,0.0
4,68617ca6246f4fbc85e91a2a49552598,offer received,0,0.00,4d5c57ea9a6940dd891ad53e9dbe8da0,0.0
...,...,...,...,...,...,...
306529,b3a1272bc9904337b331bf348c3e8c17,transaction,714,1.59,NaN,0.0
306530,68213b08d99a4ae1b0dcb72aebd9aa35,transaction,714,9.53,NaN,0.0
306531,a00058cf10334a308c68e7631c529907,transaction,714,3.61,NaN,0.0
306532,76ddbd6576844afe811f1a3c0fbb5bec,transaction,714,3.53,NaN,0.0
306533,c02b10e8752c4d8e9b73f918558531f7,transaction,714,4.05,NaN,0.0

## Load the data directly to the database

In [42]:
# import the libraries for database connection
import psycopg2
import sqlalchemy
import yaml  #store our database credentials

## Create a connection to the database: the engine!

In [45]:
with open('config.yaml', 'r') as file: # load ing the database credentials
    config = yaml.safe_load(file)

    host = config.get('host')
    user = config.get('user')
    db = config.get('database')
    password = config.get('password')
    port = config.get('port')


db_url = sqlalchemy.URL.create(
            drivername="postgresql+psycopg2",  # driver
            username=config['user'],
            password=config['password'],
            host=config.get('host', 'localhost'),
            port=config.get('port', 5432),
            database=config['database']
        )
engine = sqlalchemy.create_engine(db_url) # create the url
print(engine)
customers.to_sql('customers', engine, if_exists='replace', index=False)

offers_transformed.to_sql('offers', engine, if_exists='replace', index=False)

offers_channels.to_sql('offer_channels', engine, if_exists='replace', index=False)

events_transformed.to_sql('events', engine, if_exists='replace', index=False)

Engine(postgresql+psycopg2://postgres:***@localhost:5432/postgres)

534